# Generated by Django 5.1.7 on 2025-03-07 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_special', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=128)),
                ('is_menu', models.BooleanField(default=False)),
                ('creator_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='creators', to=settings.AUTH_USER_MODEL)),
                ('editor_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='editors', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cats', to='core.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
