# Generated by Django 5.1.7 on 2025-03-07 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aaa', '0002_remove_customuser_username_customuser_creator_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='creator_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='editor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_edited', to=settings.AUTH_USER_MODEL),
        ),
    ]
