# Generated by Django 5.2.1 on 2025-07-07 17:35

import aaa.models.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aaa', '0003_alter_customuser_creator_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=15)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', aaa.models.managers.CustomUserManager()),
            ],
        ),
    ]
