# Generated by Django 5.1.5 on 2025-07-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aaa', '0005_customuser_avatar_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, null=True, verbose_name='password'),
        ),
    ]
